"""Database CRUD for the EOD bot tables (migrations/016_eod_bots.sql)."""
from __future__ import annotations

from src.trading.repositories.bots import (
    BotNameTakenError,
    BotNotFoundError,
    DuplicateTickError,
    InvalidBotStateError,
    apply_orders_to_bot,
    create_bot,
    get_bot,
    get_bot_by_name,
    get_current_spec,
    get_open_positions,
    get_running_bots,
    insert_orders,
    insert_run_log,
    list_bots,
    record_daily_pnl,
    snapshot_positions,
    start_bot,
    stop_bot,
    update_bot_state_after_tick,
    update_run_log,
    upsert_spec_history,
)

__all__ = [
    "BotNameTakenError",
    "BotNotFoundError",
    "DuplicateTickError",
    "InvalidBotStateError",
    "apply_orders_to_bot",
    "create_bot",
    "get_bot",
    "get_bot_by_name",
    "get_current_spec",
    "get_open_positions",
    "get_running_bots",
    "insert_orders",
    "insert_run_log",
    "list_bots",
    "record_daily_pnl",
    "snapshot_positions",
    "start_bot",
    "stop_bot",
    "update_bot_state_after_tick",
    "update_run_log",
    "upsert_spec_history",
]
